### ISSUE TITLE
Script en JavaScript para migración desde Gitlab a Github

### ISSUE THREAD

**Issue by jonyram1988** [valoralabs-ltda/MigrateGitlabToGithub#1]
De acuerdo a lo conversado se requiere crear un Script en Javascript para la migración del repositorio completo desde Gitlab a Github. Esto se debe a que nosotros como VALORA LABS, desde el 14 de Junio tenemos que estar trabajando a full en Github.

- API GITLAB: https://docs.gitlab.com/ee/api/
- API GITHUB: https://developer.github.com/v3/

Actualmente existe una herramienta para la migración de repositorios, pero solamente te migra los archivos, ramas y commit. https://github.com/new/import

Lo que se espera es utilizar esta herramienta y realizar la migración de Issues, Milestone y Wiki. El orden de esperable se detalle de la siguiente forma:

1) Issues (Obligatorio)
2) Milestone (Opcional)
3) Wiki (Opcional)

Este repositorio esta público, por ende ojo con la información que se divulga...La idea es que sirva para futuros "Dev" que se encuentren en esta misma paradoja.

Finalmente comentar que la forma de trabajar es la misma de acuerdo a nuestra metodología.

¡Bienvenidos a Github!

**Comment by Anixed** [comment]
Hice un par de pruebas con los scripts que encontré y usaban versiones de api muy viejas (obsoletas) o eran muy limitadas con los datos de entrada, por lo que en nuestro caso y para proyectos más grandes quedan cortas.

Leyendo un poco la documentación de las apis de Gitlab y Github lo mejor es trabajar en una solución actualizada utilizando estas apis, aunque solo se puede hacer con los Issues y Milestones, la api de Github no soporta las Wikis (https://github.community/t5/How-to-use-Git-and-GitHub/API-for-repository-s-wiki/td-p/6706).

Lo desarrollaré en NodeJS para poder ejecutarlo vía linea de comandos.

**Comment by jonyram1988** [comment]
@asepulvedaorrego tienes alguna novedad de la idea de bitbucket?.

**Comment by jonyram1988** [comment]
> Hice un par de pruebas con los scripts que encontré y usaban versiones de api muy viejas (obsoletas) o eran muy limitadas con los datos de entrada, por lo que en nuestro caso y para proyectos más grandes quedan cortas.
> 
> Leyendo un poco la documentación de las apis de Gitlab y Github lo mejor es trabajar en una solución actualizada utilizando estas apis, aunque solo se puede hacer con los Issues y Milestones, la api de Github no soporta las Wikis (https://github.community/t5/How-to-use-Git-and-GitHub/API-for-repository-s-wiki/td-p/6706).
> 
> Lo desarrollaré en NodeJS para poder ejecutarlo vía linea de comandos.

Excelente! cualquier dato que necesites me comentas para API KEY y otros.

**Comment by asepulvedaorrego** [comment]
> @asepulvedaorrego tienes alguna novedad de la idea de bitbucket?.

Si, por ahora se replica lo mismo que en github, solo copia el repositorio pero no los issues ni los milestone, tampoco las wiki

**Comment by asepulvedaorrego** [comment]
logré importar a github los issues exportados desde gitlab gracias a esta implementación https://github.com/gavinr/github-csv-tools

para realizar las pruebas utilicé un csv exportado desde el repositorio api y haciendo unas pequeñas modificaciones a las cabeceras del csv.

las cabeceras exportadas por gitlab son las siguientes: 

```
ISSUE ID,URL,title,state,description,AUTHOR,AUTHOR USERNAME,ASSIGNEE USERNAME,assignee,CONFIDENTIAL,LOCKED,DUE DATE,CREATED AT (UTC),UPDATED AT (UTC),CLOSED AT (UTC),MILESTONE,WEIGHT,LABELS,TIME ESTIMATE,TIME SPENT

```

Originalmente todas las cabeceras vienen con letra capital, dejé las que sirven para la importación en minúscula para que las reconozca el script, actualmente la de milestone genera problemas ya que github acepta el milestone como int y gitlab lo entrega como string por lo que es mejor omitirlo en esta instancia.

la cabezera de AUTHOR y AUTHOR USERNAME se invirtieron para poder tomar el nombre de usuario correspondiente al usuario de github, para que este proceso se asigne correctamente se debe tener en consideración que el nombre de usuario en ambas plataformas debe ser el mismo.

El script genera un issue en un proyecto determinado asignándole titulo, descripción, comentarios, estado y asignados.

para los labels y asignados existe la restricción que el nombre de los datos deben ser los mismos en ambas plataformas ya que la asignación la realiza por comparación de string 

el proceso para poder utilizar el script esta descrito en el proyecto github del mismo (https://github.com/gavinr/github-csv-tools) y se realiza mediante nodeJS, el script a utilizar es: 

```
githubCsvTools myFile.csv <myFile.csv corresponde a la ubicación del archivo csv>

```

quedando de esta manera

<img width="563" alt="imagen 1" src="https://user-images.githubusercontent.com/33960670/58909389-f869f280-86e0-11e9-8198-ccaee490d4b7.png">

luego se solicita un token (creado con anterioridad) de Github del usuario que realiza la importación del los issues.

<img width="574" alt="Captura de Pantalla 2019-06-04 a la(s) 15 35 10" src="https://user-images.githubusercontent.com/33960670/58909419-0d468600-86e1-11e9-8129-7c77f67ad2a8.png">

también se solicita el usuario o la organización de quien pertenece el repositorio

<img width="570" alt="Captura de Pantalla 2019-06-04 a la(s) 15 35 19" src="https://user-images.githubusercontent.com/33960670/58909440-20595600-86e1-11e9-845c-90aae8bc2058.png">

y por ultimo el repositorio al cual asignarle los issues

<img width="573" alt="Captura de Pantalla 2019-06-04 a la(s) 15 56 54" src="https://user-images.githubusercontent.com/33960670/58909554-69a9a580-86e1-11e9-98af-acac3b85e558.png">


una vez finalizado, si todo se genera correctamente estarán creados los issues en el repo asignado.

para este caso se utilizaron issues de API, solo los abiertos (7) y se asignaron a un repositorio personal con éxito.

se adjunta de igual manera el csv utilizado para esta prueba

[valora_issue_api.csv.zip](https://github.com/valoralabs-ltda/Migrate-Gitlab-To-Github/files/3254239/valora_issue_api.csv.zip)

el token a utilizar es **ef7cb160ad22e0d3a41bfa4fb6569375110e619a** para el usuario 
**asepulvedaorrego**, se debe generar un token para valoraLabs para poder utilizar este script

**Comment by jonyram1988** [comment]
> logré importar a github los issues exportados desde gitlab gracias a esta implementación https://github.com/gavinr/github-csv-tools
> 
> para realizar las pruebas utilicé un csv exportado desde el repositorio api y haciendo unas pequeñas modificaciones a las cabeceras del csv.
> 
> las cabeceras exportadas por gitlab son las siguientes:
> 
> ```
> ISSUE ID,URL,title,state,description,AUTHOR,AUTHOR USERNAME,ASSIGNEE USERNAME,assignee,CONFIDENTIAL,LOCKED,DUE DATE,CREATED AT (UTC),UPDATED AT (UTC),CLOSED AT (UTC),MILESTONE,WEIGHT,LABELS,TIME ESTIMATE,TIME SPENT
> ```
> 
> Originalmente todas las cabeceras vienen con letra capital, dejé las que sirven para la importación en minúscula para que las reconozca el script, actualmente la de milestone genera problemas ya que github acepta el milestone como int y gitlab lo entrega como string por lo que es mejor omitirlo en esta instancia.
> 
> la cabezera de AUTHOR y AUTHOR USERNAME se invirtieron para poder tomar el nombre de usuario correspondiente al usuario de github, para que este proceso se asigne correctamente se debe tener en consideración que el nombre de usuario en ambas plataformas debe ser el mismo.
> 
> El script genera un issue en un proyecto determinado asignándole titulo, descripción, comentarios, estado y asignados.
> 
> para los labels y asignados existe la restricción que el nombre de los datos deben ser los mismos en ambas plataformas ya que la asignación la realiza por comparación de string
> 
> el proceso para poder utilizar el script esta descrito en el proyecto github del mismo (https://github.com/gavinr/github-csv-tools) y se realiza mediante nodeJS, el script a utilizar es:
> 
> ```
> githubCsvTools myFile.csv <myFile.csv corresponde a la ubicación del archivo csv>
> ```
> 
> quedando de esta manera
> 
> <img alt="imagen 1" width="563" src="https://user-images.githubusercontent.com/33960670/58909389-f869f280-86e0-11e9-8198-ccaee490d4b7.png">
> 
> luego se solicita un token (creado con anterioridad) de Github del usuario que realiza la importación del los issues.
> 
> <img alt="Captura de Pantalla 2019-06-04 a la(s) 15 35 10" width="574" src="https://user-images.githubusercontent.com/33960670/58909419-0d468600-86e1-11e9-8129-7c77f67ad2a8.png">
> 
> también se solicita el usuario o la organización de quien pertenece el repositorio
> 
> <img alt="Captura de Pantalla 2019-06-04 a la(s) 15 35 19" width="570" src="https://user-images.githubusercontent.com/33960670/58909440-20595600-86e1-11e9-845c-90aae8bc2058.png">
> 
> y por ultimo el repositorio al cual asignarle los issues
> 
> <img alt="Captura de Pantalla 2019-06-04 a la(s) 15 56 54" width="573" src="https://user-images.githubusercontent.com/33960670/58909554-69a9a580-86e1-11e9-98af-acac3b85e558.png">
> 
> una vez finalizado, si todo se genera correctamente estarán creados los issues en el repo asignado.
> 
> para este caso se utilizaron issues de API, solo los abiertos (7) y se asignaron a un repositorio personal con éxito.
> 
> se adjunta de igual manera el csv utilizado para esta prueba
> 
> [valora_issue_api.csv.zip](https://github.com/valoralabs-ltda/Migrate-Gitlab-To-Github/files/3254239/valora_issue_api.csv.zip)
> 
> el token a utilizar es **ef7cb160ad22e0d3a41bfa4fb6569375110e619a** para el usuario
> **asepulvedaorrego**, se debe generar un token para valoraLabs para poder utilizar este script

Genial. Como revisamos en conjunto con @Anixed, vamos por buen camino 😄

**Comment by jonyram1988** [comment]
@Anixed 

Para ir adelantando pega, a continuación la sincronización de usuarios desde gitlab a github.

- maria.cid: @maria-cid
- asepulvedaorrego: @asepulvedaorrego
- anixed: @Anixed
- Ambiado: @fyto
- eglade: @eglade
- Frody: @frecifue
- jonyram1988: @jonyram1988 
- vasmanuel: @vas-manuel
- Marion_Taladriz: @MarionTaladrizQ
- realaceone: @realaceone
- rodvargasflores: @rodvargasflores

**Comment by asepulvedaorrego** [comment]
@jonyram1988 @Anixed en el caso de las wikis, en caso de que no se pueda automatizar, el proceso manual es sumamente simple.

Cada Wiki trabaja como un repositorio aparte, lo que hay que hacer es descargar las wikis desde gitlab (yo lo hice con la wiki de api para realizar la prueba) y nos entregará un repositorio lleno de archivos .md (markdown)

<img width="562" alt="Captura de Pantalla 2019-06-05 a la(s) 08 58 38" src="https://user-images.githubusercontent.com/33960670/58958149-3feb8f80-8770-11e9-8d24-11e7f3bb0930.png">

por otro lado se debe generar la wiki en github para el repositorio deseado, esto nos generará otro repositorio de wiki, hay que clonarlo, agregarle todos los archivos md que estan en el repositorio entregado por gitlab 

<img width="577" alt="Captura de Pantalla 2019-06-05 a la(s) 08 58 53" src="https://user-images.githubusercontent.com/33960670/58958171-51349c00-8770-11e9-803e-71c64238c7be.png">

y luego hacer un push por consola

<img width="524" alt="Captura de Pantalla 2019-06-05 a la(s) 09 01 38" src="https://user-images.githubusercontent.com/33960670/58958291-95c03780-8770-11e9-93af-59105b167f47.png">

con ese proceso, quedará toda la wiki arriba en el repositorio de destino

![Captura de Pantalla 2019-06-05 a la(s) 09 00 40](https://user-images.githubusercontent.com/33960670/58958213-690c2000-8770-11e9-8ef8-1d3ea1d60a23.png)

**Comment by jonyram1988** [comment]
Tarea terminada.
